In [6]:
import pandas as pd

In [7]:
files = ['../Data/Commodities by visitors/CommodityByVisitors2018.csv', 
         '../Data/Commodities by visitors/CommodityByVisitors2019.csv', 
         '../Data/Commodities by visitors/CommodityByVisitors2020.csv', 
         '../Data/Commodities by visitors/CommodityByVisitors2021.csv', 
         '../Data/Commodities by visitors/CommodityByVisitors2022.csv', 
         '../Data/Commodities by visitors/CommodityByVisitors2023.csv']

In [8]:
dfs = []
for file in files:
    df = pd.read_csv(file)
    year = int(file.split('CommodityByVisitors')[1].split('.csv')[0])
    df['Year']= year
    dfs.append(df)

In [9]:
visitor_type_merged_df = pd.concat(dfs, ignore_index=True)

In [10]:
visitor_type_merged_df.to_csv('../CommodityByVisitors.csv', index=False)

In [11]:
visitor_type_merged_df

,Commodity,Total consumption,Resident households,Business,Government,Nonresidents,Total tourism demand,Nontourism demand,Tourism commodity ratio,Year
0,Traveler accommodations,"228,327","109,070","71,631","6,568","41,058","228,327",0,1.00,2018
1,Food and beverage services,"998,014","84,117","40,934","4,766","24,252","154,069","843,944",0.15,2018
2,Domestic passenger air transportation services,"167,622","103,239","48,734","15,620",29,"167,622",0,1.00,2018
3,International passenger air transportation ser...,"102,623","35,571","24,965","1,625","40,462","102,623",0,1.00,2018
4,Passenger rail transportation services,"2,403","1,193",966,244,0,"2,403",0,1.00,2018
...,...,...,...,...,...,...,...,...,...,...
151,All other recreation and entertainment,"98,692",460,"11,123",0,157,"11,740","86,952",0.12,2023
152,Gasoline,"594,463","108,908","35,428","1,172","3,049","148,556","445,907",0.25,2023
153,Shopping,"5,847,853","182,256","52,767","2,058","33,922","271,004","5,576,849",0.05,2023
154,All other commodities,"41,949,336",0,0,0,0,0,"41,949,336",0.00,2023
155,Travel by U.S. residents abroad,"144,747","132,321","12,426",0,0,"144,747",0,1.00,2023

In [12]:
visitor_type_merged_df.to_csv('commodities_by_visitor_type.csv')

In [13]:
melted_df = pd.melt(visitor_type_merged_df,
                    id_vars=['Commodity', 'Total consumption', 'Total tourism demand',
                             'Nontourism demand', 'Tourism commodity ratio', 'Year'],
                    value_vars=['Resident households', 'Business', 'Government', 'Nonresidents'],
                    var_name='Visitor Type',
                    value_name='Demand')

melted_df

,Commodity,Total consumption,Total tourism demand,Nontourism demand,Tourism commodity ratio,Year,Visitor Type,Demand
0,Traveler accommodations,"228,327","228,327",0,1.00,2018,Resident households,"109,070"
1,Food and beverage services,"998,014","154,069","843,944",0.15,2018,Resident households,"84,117"
2,Domestic passenger air transportation services,"167,622","167,622",0,1.00,2018,Resident households,"103,239"
3,International passenger air transportation ser...,"102,623","102,623",0,1.00,2018,Resident households,"35,571"
4,Passenger rail transportation services,"2,403","2,403",0,1.00,2018,Resident households,"1,193"
...,...,...,...,...,...,...,...,...
619,All other recreation and entertainment,"98,692","11,740","86,952",0.12,2023,Nonresidents,157
620,Gasoline,"594,463","148,556","445,907",0.25,2023,Nonresidents,"3,049"
621,Shopping,"5,847,853","271,004","5,576,849",0.05,2023,Nonresidents,"33,922"
622,All other commodities,"41,949,336",0,"41,949,336",0.00,2023,Nonresidents,0
623,Travel by U.S. residents abroad,"144,747","144,747",0,1.00,2023,Nonresidents,0

In [14]:
melted_df.to_csv('commodities_by_visitor_melted.csv')